apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
        - env:
            - name: VUE_APP_API_URL
              value: http://34.90.153.190:3000
          image: yoannpaquereau/mevn-client
          name: client
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
