version: '3'
services:
  server:
    image: node:14
    container_name: server
    volumes:
      - ./server:/src/app
    links:
      - db:db
    ports:
      - 3000:3000
    command: bash -c "npm install -g nodemon && cd /src/app && npm install && nodemon server"

  client:
    image: node:14
    container_name: client
    volumes:
      - ./client:/src/app
    ports:
      - 8080:8080
    links:
      - server:server
    command: bash -c "cd /src/app && npm install && npm run serve"

  db:
    image: mongo
    container_name: db
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root