version: '3'
services:
  server:
    image: yoannpaquereau/mevn-server
    container_name: server
    links:
      - db
    ports:
      - 3000:3000    

  client:
    image: yoannpaquereau/mevn-client
    container_name: client
    ports:
      - 8080:8080
    environment:
      - VUE_APP_API_URL=http://34.90.153.190:3000

  db:
    image: mongo
    container_name: db
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017