version: '3'
services:
  server:
    image: mevn-server
    container_name: server
    volumes:
      - ./server:/src/app
    links:
      - db:db
    ports:
      - 3000:3000

  client:
    image: mevn-client
    container_name: client
    volumes:
      - ./client:/src/app
    ports:
      - 8080:8080

  db:
    image: mongo
    container_name: db
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root